### PR TITLE
chore: add cross-env to support windows env set

### PR DESCRIPTION
**Pull request by moonrailgun**

### CODE REVIEW

**Comment by yinxin630** [comment]
请确认一下, 这块代码 <https://github.com/yinxin630/fiora/blob/master/build/webpack.common.js#L46> 在使用 `cross-env` 后, 分别执行 `yarn dev:client` 和 `yarn build:client` 时能获取到正确的 `NODE_ENV` 值

**Comment by moonrailgun** [comment]
image

image

image

I am sure very very much. I have used `cross-env` for a long time

**Comment by yinxin630** [comment]
Please rebase from master before merge it

**Comment by moonrailgun** [comment]
@yinxin630 This pr is ready for merge

**Comment by yinxin630** [comment]
Thank you very much for your contribution 😃

**Pull request merged**
